### ISSUE TITLE
Time range change feedback

### ISSUE THREAD

**Issue by matthiasr** [prometheus/promdash#153]
Currently, there is no visual feedback after clicking the +/- buttons to change the time range, until all the graphs are updated. I tend to click several times then and wildly overshoot.

As a minimal feedback, the time displayed should change before any potentially long-running action is taken. Even better would be to then start by scaling all the graphs, even if there is no new data to fill them in– then, the waiting time until this data is read and rendered will even contribute to a "smooth" transition; seeing the current graphs "shrink" should give a visual cue to the zooming "motion".

**Comment by grobie** [comment]
Solved with #290.
