### ISSUE TITLE
Keep browser URL always updated

### ISSUE THREAD

**Issue by grobie** [prometheus/promdash#203]
> As a user,
> I want to copy the dashboard URL with the current time settings,
> so that I can send it to others during an outage investigation.

It currently takes several clicks to get an URL with the range/until params set.

Proposal:
* remove the "keep browser URL updated" checkbox
* always add the parameters to the URL on change

Disadvantages: The URL gets longer. If someone really only wants to get the base URL _after_ manually changing the range settings, they need to only select a part of the URL in the address bar. Not sure if that's an issue.

Alternative proposal:
* add a new button "get permalink"

**Comment by stuartnelson3** [comment]
closed by #245
