### ISSUE TITLE
x-axis zoom

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/promdash#241]
http://code.shutterstock.com/rickshaw/examples/extensions.html

cc/ @jdarc

**Comment by grobie** [comment]
The "drag&zoom" introduction blog post: http://blog.newrelic.com/2011/07/15/drag-and-zoom-for-great-justice/

**Comment by stuartnelson3** [comment]
@grobie @juliusv priority level on this?

**Comment by juliusv** [comment]
I'm fine with this in general, though everything depends on cost of implementation and maintenance. I'll leave that judgement and the prioritization up to @grobie and you :)

I would also prefer the NewRelic way of doing things, even though it doesn't exist as a finished Rickshaw component yet. It feels more natural, and it also requires less UI space. However, one should be careful to get the details right: e.g. how to zoom out (or maybe not necessary in v1)?

**Comment by grobie** [comment]
I have never seen any short cut to zoom out. It'll still be possible to change the date with the existing options, so I don't see zoom out to be part of the scope of this feature. One can also simply reloading the page to reset the default range/until.

**Comment by grobie** [comment]
This is one of the most kick-ass features in promdash. Very well done @stuartnelson3! ^5

![Approved](http://media.giphy.com/media/BQAk13taTaKYw/giphy.gif)
