### ISSUE TITLE
Redraw graph when selecting/deselecting timeseries

### ISSUE THREAD

**Issue by grobie** [prometheus/promdash#258]
Scenario:
3 timeseries: a with values ~220k, b and c with values ~1000-1500

Current:
Deselecting the label (clicking on the tick in the legend) only hides a timeseries, without redrawing the graph based on the new values / changing the axis.

Expected:
Redraw the graph, so that timeseries with small values become visible.

Related:
* grafana: expected behavior
* newrelic: expected behavior

**Comment by peterbourgon** [comment]
:+1:

**Comment by juliusv** [comment]
Haven't looked at how easy it is to do this, but :+1:
