### ISSUE TITLE
Preserve state of legend selection

### ISSUE THREAD

**Issue by grobie** [prometheus/promdash#259]
Steps:
- open dashboard
- activate refresh for a specific interval
- select/deselect a time series in a graph (using the legend menu)

Expected:
- selection doesn't change after graph refresh

Observed:
- graph refreshes, selection state is lost and needs to be redone.

**Comment by juliusv** [comment]
I can imagine this won't be super straightforward to implement, but :+1: in principle.

**Comment by stuartnelson3** [comment]
each time a graph refreshes, a the old graph is being destroyed and a new graph is being drawn in its place; there is no knowledge between graphs of legend state.

how vital is this? we would have to maintain the state separately, which sounds messy and probably error prone.

**Comment by stuartnelson3** [comment]
closed by #263
