### ISSUE TITLE
Handle orphaned data source gracefully

### ISSUE THREAD

**Issue by grobie** [prometheus/promdash#276]
Without an option to delete associated data sources upon a server delete as requested in #239, it's currently easily possible to break a dashboard/graph without an option for the user to fix the broken state. 

Promdash has to handle the case of an orphaned widget gracefully, so that a user can still change/delete the dashboard data. A widget is currently completely broken and can't be deleted anymore. Maybe it makes sense to use the error handling UI for invalid expressions to indicate a missing data source and allow the user to change the server or delete the data source altogether.

---

Example:

```
TypeError: Cannot read property 'url' of undefined
```

![screenshot from 2015-01-11 14 07 16](https://cloud.githubusercontent.com/assets/3432/5695303/718ff5b6-999b-11e4-848b-16c604850b71.png)

**Comment by juliusv** [comment]
It used to be that deleting a server simply set the server selection box of an expression to "unselected", but didn't break anything. Seems like this is a regression.
