### ISSUE TITLE
Proposal: progressive evaluation of global setting changes

### ISSUE THREAD

**Issue by peterbourgon** [prometheus/promdash#285]
If I have a promdash with many graphs, and I make a change to a global setting, like time range, the interface freezes for quite some time, as all of the graphs are updated simultaneously. I'm not able to move my cursor, etc.

I'm ultimately interested in solving that slowdown. Maybe one way could be serially applying the changes to each graph, rather than mutating them all at the same instant. But if you have better ideas, please do tell...

**Comment by juliusv** [comment]
For my understanding: so far, I've only seen that the interface doesn't respond, but cursor movements are still possible. You really can't move your mouse cursor anymore? The former would be due to JS's single-threadedness, but the latter would say your entire machine is overloaded.

**Comment by peterbourgon** [comment]
By cursor I mean the input cursor in the interface, for example using the arrow keys to move the cursor in the time range field. The mouse cursor moves fine.

**Comment by stuartnelson3** [comment]
This is definitely possible. However, how we handle it can be decided upon. To do a single graph at a time seems laborious to me.

We ~could~ do some fun stuff with `navigator.hardwareConcurrency` to detect the number of cores a machine has and scale the number of concurrent requests. this seems a bit poorly thought out though, as using this value is only to infer that a higher concurrency level also means they most likely have a higher processor speed.

alternatively, i could try to rig up something where graphs only get loaded when in view? e.g., load graphs as soon as they are in view, otherwise load them one row at a time (row being the user defined dashboard row, so anywhere from 1 to 3 or 4 widgets at a time)

**Comment by peterbourgon** [comment]
> To do a single graph at a time seems laborious to me.

What do you mean by laborious? Doing all graphs simultaneously is quite laborious for my CPU :)

> fun stuff with `navigator.hardwareConcurrency` . . . scale the number of concurrent requests.

My intuition is that the browser is getting overloaded trying to do so many concurrent tasks. What's the "concurrency level" now? —can we reduce it to 1, and see how that behaves? 

> i could try to rig up something where graphs only get loaded when in view?

Hmm, I'd prefer not having "pop-in" artifacts on scroll. Many promdashes have 15+ graphs in view at once, anyhow.

**Comment by stuartnelson3** [comment]
> What do you mean by laborious? Doing all graphs simultaneously is quite laborious for my CPU :)

heh, sorry: laborious as in watching each each graph load a la dominos falling

> My intuition is that the browser is getting overloaded trying to do so many concurrent tasks. What's the "concurrency level" now? —can we reduce it to 1, and see how that behaves?

concurrency level is a read-only value based on your personal hardware's number of cores. I believe, as @juliusv mentioned, that the browser's js vm still runs as a single-threaded event loop. I have not looked at it, but [web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/basic_usage) allow for background work to be done. This could either:
- allow for a separate worker to handle all async requests, freeing up the main thread
- allow a separate worker to spawn sub-workers to process each separate request

I have no experience with this, and it's new technology, but it's supported in chrome/ff/safari, which covers every browser used by developers.

> Hmm, I'd prefer not having "pop-in" artifacts on scroll. Many promdashes have 15+ graphs in view at once, anyhow.

so, avoiding pop-in, how does loading a row at a time sound?

**Comment by peterbourgon** [comment]
> laborious as in watching each each graph load a la dominos falling

I guess I'd prefer that to the current behavior. It'd give me a sense of progression while (hopefully) keeping my browser responsive.

> how does loading a row at a time sound?

Worth a shot!

**Comment by grobie** [comment]
@peterbourgon How is the situation these days for you?

**Comment by peterbourgon** [comment]
I haven't seen the original problem in quite some time.
