### ISSUE TITLE
Error encoding an entiry dashboard in URL

### ISSUE THREAD

**Issue by grobie** [prometheus/promdash#288]
Encoding an entire dashboard in base64 can easily exceed 4096 bytes which is a typical limit for URLs. 

As this makes these links useless, I suggest to save the dashboard URLs similar to graph URLs in database.

**Comment by stuartnelson3** [comment]
if a user keeps the url updated, that would require an async request every time something in the dashboard changes to persist this, and it would also require some form of indicator in the URL that indicates to the UI to load from a particular place.

are you proposing to maintain the current functionality, but back the data in the database? or would it be a button somewhere, like "get link for this dashboard", and then it generates the link (pretty much exactly like the graph link)

**Comment by juliusv** [comment]
AFAIK the max length of the hash part (fragment identifier) is unspecified
because it's not actually sent over HTTP, but only used locally.

I tried storing 1MB in the hash in Firefox and it worked fine to retrieve
it. Chrome's UI gets a bit sluggish at those sizes, but at least I was able
to verify that I was able to store 32k in the hash in Chrome. So maybe this
isn't really a big problem so far.

**Comment by stuartnelson3** [comment]
close-able?

**Comment by juliusv** [comment]
I'd wait to see what @grobie thinks :)

If the hash does turn out to be a problem, we could simply offer a
"permalink" button that only generates a permalink when requested instead
of constantly creating it upon every change.

**Comment by grobie** [comment]
I can't paste such URL in irc, it fills so many lines in emails that I
neither feel comfortable to use it there and it's also too long for
SoundCloud's internal link shortener. This makes this feature completly
useless to me. While I don't think it needs a high priority, I consider
this to be a problem.

A permalink button sounds fine, no need for dynamic updates. I started to
clone dashboards as a workaround.
I'd wait to see what @grobie thinks :)

If the hash does turn out to be a problem, we could simply offer a
"permalink" button that only generates a permalink when requested instead
of constantly creating it upon every change.

On Fri, Jan 23, 2015 at 1:06 PM, stuart nelson <notifications@github.com>
wrote:

> close-able?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/prometheus/promdash/issues/288#issuecomment-71184691>.

>

--
Reply to this email directly or view it on GitHub
<https://github.com/prometheus/promdash/issues/288#issuecomment-71191594>.

**Comment by juliusv** [comment]
Ok, agreed.

**Comment by stuartnelson3** [comment]
closed by #296
