### ISSUE TITLE
Watch URL for changes

### ISSUE THREAD

**Issue by grobie** [prometheus/promdash#289]
If anything in the URL gets changed, these values should be reloaded in the dashboard. For example on change of a `var.<template var>`.

**Comment by stuartnelson3** [comment]
I can't detect simply changing attrs in the location bar and updating the UI. I can detect changes if you hit "enter" after making your changes.

is that good?

**Comment by grobie** [comment]
Yes, that sounds fine.

Duplicate of #204.
