### ISSUE TITLE
Mouse-zooming feature too addictive

### ISSUE THREAD

**Issue by juliusv** [prometheus/promdash#311]
Since the introduction of the zooming feature in https://github.com/prometheus/promdash/pull/284 I have not been able to use PromDash properly. Whenever I open a dashboard, I just start playing with the mouse zoom, zoom in, and out, and zoom in again... and out... and in... stuck in an addictive loop and totally spaced out. Until I finally wake up after 10 minutes or so and can't remember what I initially set out to do. This seriously affects my ability to do actual work. Please fix.

**Comment by grobie** [comment]
Feature creep. Sorry.

**Comment by juliusv** [comment]
![ok...](http://replygif.net/i/101.gif)

**Comment by grobie** [comment]
![](http://media.giphy.com/media/PR2hzEXVXrPnG/giphy.gif)
