### ISSUE TITLE
Allow embedding dashboards/graphs into other pages

### ISSUE THREAD

**Issue by grobie** [prometheus/promdash#33]
Similar to the SoundCloud widget, or in prometheus context to the NewRelic widget, it'd be nice being able to embed dashboards in other pages for quick access. Examples I came across are collins, our asset management system (dashboard which shows metrics about load, memory usage, uptime, network latency, etc.), cloudmaker (our virtual machine manager), bazooka dashboards, etc.

As there probably won't be always enough space to show all dashboard graphs at once, I could imagine a possible widget layout would only show one graph at a time but also an additional select field to switch between the various graphs of a dashboard. The widget should also include the title and a link to the dashboard for all the additional data inspection beyond the first glimpse.

The dashboards itself should have a button to show the embed code, probably some html snippet using an iframe like we do with the SoundCloud widget.

**Comment by mbrevoort** [comment]
@juliusv where did the docs from the wiki move?

**Comment by beorn7** [comment]
http://prometheus.io/docs/visualization/promdash/#embedding-a-dashboard

**Comment by felixfbecker** [comment]
where did the docs from prometheus.io move?

**Comment by juliusv** [comment]
@felixfbecker PromDash docs got removed in https://github.com/prometheus/docs/pull/683. PromDash had already been deprecated for a while at that time.
