### ISSUE TITLE
Obvious "close" button on popups

### ISSUE THREAD

**Issue by matthiasr** [prometheus/promdash#330]
Often, when I have any popup or menu open, I am looking for an easy, visually obvious way out. I think it would make most sense to just have an X on every popup, like this:

![mr-temp___prometheus_dashboard](https://cloud.githubusercontent.com/assets/131590/6145819/d988094c-b1dd-11e4-9f2f-01a840f48eaf.png)
![mr-temp___prometheus_dashboard](https://cloud.githubusercontent.com/assets/131590/6145829/eda60adc-b1dd-11e4-9c85-93bbd87b7a34.png)
![mr-temp___prometheus_dashboard](https://cloud.githubusercontent.com/assets/131590/6145840/0af380c4-b1de-11e4-83fb-2dc0c2078e07.png)

**Comment by discordianfish** [comment]
:+1: Maybe we should also close it if you click anywhere outside the popup?

**Comment by matthiasr** [comment]
I second that!

**Comment by juliusv** [comment]
Leaving decisions on this one up to @stuartnelson3 (including yay or nay or how). Just FWIW, Escape already closes any popups.

Just a thought about closing popups when clicking somehwere else: sometimes you don't want that, such as when you're copying expressions from one graph to another and you want panes in both graphs to stay open for that.

**Comment by discordianfish** [comment]
> Just a thought about closing popups when clicking somehwere else: sometimes you don't want that, such as when you're copying expressions from one graph to another and you want panes in both graphs to stay open for that.

Fair enough, but you never want to click on graphs or the background without the popup closing, right? So I would close it unless you click on any other popup or menu.

@juliusv

**Comment by grobie** [comment]
:+1: to icon and "close on click on background".

At least for data sources and dashboard settings it should be easy. Time settings might be harder, as it's a) a plugin afaik and b) visually there is no space available right now. Maybe not strictly necessary?

**Comment by stuartnelson3** [comment]
regarding time settings:

- it is a plugin
- we don't have much control over the visuals as a result (and there is no space)
- but, it already closes when you click outside it

**Comment by matthiasr** [comment]
Another cue that came to mind, and might help for the time menu (which I wouldn't mind changing …) – highlight the button that opened (and will close) it, so that it is visibly anchored to it. That would make it feel more like a menu than a button, and show where it came from. This applies to the other menu/popups as well.

**Comment by stuartnelson3** [comment]
closed by #347
