### ISSUE TITLE
Auto-refresh when changing servers

### ISSUE THREAD

**Issue by grobie** [prometheus/promdash#352]
If a different server gets selected, the graph should be auto-refreshed immediately, like it happens when changing time.

**Comment by juliusv** [comment]
This is actually not specific to the server selection - we currently don't refresh the data automatically for any of the per-graph inputs (including time). I think it should refresh automatically for:

* changing time settings
* changing the resolution
* changing the server
* when pressing enter in the expression input (but not when just changing it, I guess - it would be too noisy)

**Comment by matthiasr** [comment]
Seconded! It's annoyingly hard to get a new expression to evaluate.

**Comment by grobie** [comment]
Thanks!
