### ISSUE TITLE
clone dashboards with server X

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/promdash#355]
use case:

I want to clone a dashboard for a different cluster. all the graphs are the same, but the server for each widget is different.

remove the tedium of manually updating every widget.

**Comment by grobie** [comment]
Instead of a clone option, can we please just have a global server option? We do the same for time range and until: have a global option, allow per widget overrides. I believe it should be the same for dashboards: have a global one, allow override per widget.

**Comment by stuartnelson3** [comment]
interesting. would this be always visible, like the time range and until selectors, or would it be hidden in the dashboard config with e.g. colorscheme?

would this be something you want to override with a URL param? `promdash.com/my-dashboard#?server=my-awesome-server`

**Comment by grobie** [comment]
Well ... #202 solves all these questions :p

Setting it per URL parameter might be great. Makes the question even bigger how to provide shortlinks for specific promdash/dashboard?lots=of&variables=set&server=chosen URLs.

**Comment by grobie** [comment]
Will be solved by #180.
