### ISSUE TITLE
cardinal interpolation overshoots

### ISSUE THREAD

**Issue by cryptix** [prometheus/promdash#356]
Hi,

is this behaviour in cardinal interpolation expected? I looks like the boundaries are wrong.

linear:
![interpol2](https://cloud.githubusercontent.com/assets/111202/6389050/810a5f80-bda0-11e4-9fe6-98225cc2c9f5.png)
cardinal:
![interpol1](https://cloud.githubusercontent.com/assets/111202/6389051/810d0e7e-bda0-11e4-95d3-894664f7fd04.png)

**Comment by stuartnelson3** [comment]
so, the code that handles the interpolation is here: https://github.com/prometheus/promdash/blob/a4cbe3f50273181285b1655f36f929c04826d30d/app/assets/javascripts/angular/directives/graph_chart.js#L219-L225

this is just a setting in rickshaw, which in turn is sent directly into d3:
https://github.com/shutterstock/rickshaw/blob/a240899625c2d83961b3e682cd77ab8e5199a866/src/js/Rickshaw.Graph.Renderer.Line.js#L20-L23

so, while I agree that it looks goofy, I have to believe that it's working correctly (and I can't do anything to change it).

**Comment by cryptix** [comment]
okay, perfectly reasonable. I just wanted to make sure this isn't a fluke.
