### ISSUE TITLE
Allow deploying to heroku.

### ISSUE THREAD

**Issue by tomprince** [prometheus/promdash#359]
It seems like this is almost able to be able to be deployed, but the application fails to start.

**Comment by tomprince** [comment]
Mostly, I'd like to be able to easily install without
- installing anything (docker would also work)
- without configuring a database.

**Comment by stuartnelson3** [comment]
what error message do you receive from heroku?

**Comment by juliusv** [comment]
@tomprince Besides @stuartnelson3's question: Regarding Docker, there is already a Dockerfile included in the repo root, and ready-to-use Docker images at https://hub.docker.com/u/prom/.

**Comment by stuartnelson3** [comment]
@juliusv i think this is done. if you agree, go ahead and close :)

**Comment by juliusv** [comment]
As far as I can see, yes. So I'll close it. Please reopen if it's still relevant.
