### ISSUE TITLE
Ruby hangs / freezes after idle in docker container

### ISSUE THREAD

**Issue by dougrad** [prometheus/promdash#371]
I'm running promdash from the official Docker container, with a remote MySQL database. It works fine on first startup, but within an hour becomes unresponsive.  The listen port accepts a connection but doesn't respond, and no further activity is logged. I tried sending logs to a file instead of stdout.  Prometheus and Alertmanager in the same environment work fine.  Any ideas?

**Comment by juliusv** [comment]
No idea from my side (and not using Docker). @discordianfish Have you ever witnessed something like this using PromDash in Docker?

**Comment by discordianfish** [comment]
No, not really. @dougrad To rule out a problem with docker (well, or to make it less likely), can you try to reach the listen port via the docker internal IP of the container?
Basically: `curl $(docker inspect -f '{{.NetworkSettings.IPAddress}}' [your-container])`:3000

**Comment by dougrad** [comment]
Problem has cleared up - I suspect problems with queries hanging on the mysql end. Thanks for the comments!
