### ISSUE TITLE
Dashboard delete broken

### ISSUE THREAD

**Issue by grobie** [prometheus/promdash#376]
Just opens the show page. Missing _method?

Let's create an acceptance test for it first.

**Comment by stuartnelson3** [comment]
Unfortunately, there IS a spec:

https://github.com/prometheus/promdash/blob/master/spec/features/dashboards_spec.rb#L145-L155

and it passes.

The issue is, as part of our new split between base.js and application.js, base.js doesn't exist in production.

**Comment by stuartnelson3** [comment]
fixed by https://github.com/prometheus/promdash/commit/73515218b57662f6208fc1c752805d8291e25ede
