### ISSUE TITLE
Assets precompile - database connection

### ISSUE THREAD

**Issue by piotrkowalczuk** [prometheus/promdash#379]
`make build` fail on

```
bin/env bin/bundle exec rake assets:precompile
rake aborted!
Gem::LoadError: Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
```

Since my goal is to build it on jenkins and then put archive on production server i would like to avoid any db connection. Any ideas?

**Comment by juliusv** [comment]
Hmmm, this sounds like a general Rails question (how to precompile assets without making Rails think it needs to load a database driver). Maybe something like in http://stackoverflow.com/questions/821251/how-to-configure-ruby-on-rails-with-no-database?

@grobie Any ideas?

**Comment by stuartnelson3** [comment]
is `sqlite3` in the bundle for your `RAILS_ENV` when running this?

**Comment by juliusv** [comment]
Yeah, and after https://github.com/prometheus/promdash/pull/386, `bundle` should now by default install the `sqlite3` gem for you for any Rails env? And it won't touch an actual database over the network, only the local sqlite3 DB in the worst case.

**Comment by grobie** [comment]
Until it Rails 4 it was possible to disable the initialization of the app (and therefore database connection). It seems they removed that option in Rails 4. This is not specific to promdash, but a general Rails issue. Though, it should be possible to build the assets with an empty sqlite3 database.

**Comment by matthiasr** [comment]
Just tested and it seems #386 fixes this. I just copied the database.yml.example to database.yml.

**Comment by matthiasr** [comment]
PS: if you don't want to deal with the on-disk sqlite database, use this `database.yml`:

```yml
development:
  adapter: sqlite3
  database: ":memory:"
  pool: 5
  timeout: 5000
```

I haven't tested it for anything but asset generation, but in other projects I've had good experiences running tests against it.
