### ISSUE TITLE
Selecting metric from suggestions closes datasources form

### ISSUE THREAD

**Issue by grobie** [prometheus/promdash#380]
Steps:
* Add new graph
* open "Datasources"
* start typing metric name
* click on suggestion (works when selecting by keyboard)

Observed:
* datasources form closes
* graph is not refreshing immediately

Expected:
* form doesn't close
* graph may refresh, but probably shouldn't to not load too much data

**Comment by juliusv** [comment]
:+1:

**Comment by juliusv** [comment]
This also happens for other buttons, like the `[x]` button for removing an expression, or for removing a legend format string.
