### ISSUE TITLE
Permalink dashboards appear in clone menu dashboard selector

### ISSUE THREAD

**Issue by juliusv** [prometheus/promdash#385]
When cloning widgets from another dashboard, the dashboard selector also contains permalink dashboards:

![promdash_clone](https://cloud.githubusercontent.com/assets/538008/7201450/881f68c2-e507-11e4-90b0-a66a56339940.png)

It should only show non-permalink dashboards.

**Comment by stuartnelson3** [comment]
fixed by https://github.com/prometheus/promdash/commit/a41312
