### ISSUE TITLE
Cancelling the insertion of a frame breaks the UI

### ISSUE THREAD

**Issue by quinox** [prometheus/promdash#388]
Tested against HEAD (98f955c):

* Open a dashboard
* Click on "Add frame"
* Press cancel
* Get a stacktrace in your terminal starting with: `Error: url is null`
* The newly created elements can't be interacted with.

![broken promdash](http://ghost.qtea.nl/tmp/broken_promdash.png)

**Comment by juliusv** [comment]
:+1: thanks for reporting!

**Comment by stuartnelson3** [comment]
hehe been a bug since `2013-12-19` :P
