### ISSUE TITLE
Can't get annotations to work

### ISSUE THREAD

**Issue by oliver006** [prometheus/promdash#392]
I followed the instructions on http://prometheus.io/docs/visualization/promdash/ and have my annotation server return annotations via json but I can't get them to show up on promdash.
I see promdash making the request to the annotation server to fetch the tags but then it throws a JS error in the console:

![screen shot 2015-05-01 at 4 24 10 pm](https://cloud.githubusercontent.com/assets/1222339/7438308/0df3c276-f030-11e4-934a-4246fa08b5d6.png)

My annotation JSON looks something like that:
```
{
  "deploy": [
    {
      "created_at": 1430506058,
      "message": "hello"
    }
  ],
  "build": [
    {
      "created_at": 1430510738,
      "message": "also hello"
    }
  ]
}
```
Browser retrieves it from promdash just fine:
![screen shot 2015-05-01 at 6 29 01 pm](https://cloud.githubusercontent.com/assets/1222339/7438306/06ade94c-f030-11e4-8b8b-0c49b4350f8e.png)

Let me know what else I can provide to help diagnosing this.

**Comment by stuartnelson3** [comment]
The key needs to be `posts`:

```
{
  posts: [
    {
      created_at: 111232553, // UNIX timestamp
      message: "annotation message here"
    },
    // ... more tags
  ]
}
```

`posts` does not indicate what you are querying for. it is an object with a `posts` key, whose value is an array containing as many annotations as you like (your annotation data structure is correct).

**Comment by oliver006** [comment]
Thanks Stuart, that helped.
I found another issue, the docs say promdash expects a unix timestamp but it doesn't say that the timestamp needs to be in milliseconds, not seconds.

I got another question regarding the `tags[]`filter, the docs say it can occur several times but I saw promdash do a separate request for each tag that I added in the UI. Is that expected?

**Comment by stuartnelson3** [comment]
>I found another issue, the docs say promdash expects a unix timestamp but it doesn't say that the timestamp needs to be in milliseconds, not seconds.

Noted, thanks!

>I got another question regarding the tags[]filter, the docs say it can occur several times but I saw promdash do a separate request for each tag that I added in the UI. Is that expected?

You can add multiple annotation tag fields, as you've noticed. However, within a single field, you can enter a comma-separated list to construct a query that filters by multiple tags.

something like this (can't remember exactly):

`someTag` => `GET www.endpoint.com/?tags[]=someTag`

`oneTag, anotherTag` => `GET www.endpoint.com/?tags[]=oneTag&tags[]=anotherTag`

code is [here](https://github.com/prometheus/promdash/blob/master/app/assets/javascripts/angular/services/annotation_refresher.js.erb)

**Comment by oliver006** [comment]
Thanks again Stuart, that's very helpful!

**Comment by oliver006** [comment]
I got the annotation server to work (it's available here: https://github.com/oliver006/prom_annotation_server) so let me close this.
