### ISSUE TITLE
"Link to Graph in Prometheus" only works when server url was configured with trailing /

### ISSUE THREAD

**Issue by quofelix** [prometheus/promdash#425]

**Comment by sdurrheimer** [comment]
This is mentioned in the documentation. 
http://prometheus.io/docs/visualization/promdash/#registering-a-prometheus-server

**Comment by juliusv** [comment]
That should definitely be fixed anyways (and reference then removed from the docs). It was already fixed in most other places, but apparently not in this place yet.

**Comment by juliusv** [comment]
@stuartnelson3
