### ISSUE TITLE
promdash: undefined method `server_type`

### ISSUE THREAD

**Issue by miekg** [prometheus/promdash#436]
If you start a newish promdash docker container and click on the servers tab, you get:

```
ActionView::Template::Error (undefined method `server_type' for #<Server:0x007f2913308890>):
    22:       <tr>
    23:         <td><%= server.name %></td>
    24:         <td><a href="<%= server.url %>"><%= server.url %></a></td>
    25:         <td><%= server.server_type.capitalize %></td>
    26:         <td>
    27:           <%= link_to 'Edit', edit_server_path(server) %>
    28:           &nbsp;&nbsp;
  app/views/servers/index.html.erb:25:in `block in _app_views_servers_index_html_erb__1521961733507216670_69907196609960'
  app/views/servers/index.html.erb:21:in `_app_views_servers_index_html_erb__1521961733507216670_69907196609960'
```

**Comment by miekg** [comment]
This seems to be related (I think)
```
application-7317432d3065f854276c2e0d463e37bd.js:1828 TypeError: loadGraphData[server.server_type] is not a function
    at http://localhost:3000/assets/application-7317432d3065f854276c2e0d463e37bd.js:4541:49
```

Which in turn makes none of the dashboard load.

**Comment by juliusv** [comment]
Probably an existing database that just needs a migration to add the new `server_type` column?

Did you run this kind of migration step after the upgrade?

```
docker run -v /tmp/prom:/tmp/prom -e DATABASE_URL=sqlite3:/tmp/prom/file.sqlite3 prom/promdash ./bin/rake db:migrate
```

**Comment by miekg** [comment]
Ah, yes that makes sense. Thanks.

Except we don't store this in sqlite3, but in a central database.... The change is probable *not* backwards compatible?

**Comment by juliusv** [comment]
Yeah, you'd have to adjust the paths and `DATABASE_URL` in that example to your setup. For MySQL, that would e.g. be `mysql2://<user>:<pass>@<host>/<dbname>` (you'll already have this somewhere as part of your running PromDash setup).

Not sure about backwards compatibility. As long as you don't create any Graphite servers (which is the new feature enabled by this new column), you might be able to roll back the migration without breaking anything. But haven't tested that, and in general I'd always advise making a DB backup before rolling out a new PromDash version and/or running migrations.

**Comment by juliusv** [comment]
Closing the issue here.

**Comment by miekg** [comment]
Thanks for your SRE advice :)
