### ISSUE TITLE
bundle install does not compile sqlite-1.3.8 with ubuntu-server-14.04 lts

### ISSUE THREAD

**Issue by ne0h** [prometheus/promdash#441]
While installing Promdash with ubuntu server 14.04 I noticed that `./bin/bundle install` does not compile. Error is:

`Installing sqlite3 1.3.8 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/local/rvm/rubies/ruby-2.2.2/bin/ruby -r ./siteconf20150813-624-c0xhek.rb extconf.rb
checking for sqlite3.h... yes
checking for sqlite3_libversion_number() in -lsqlite3... yes
checking for rb_proc_arity()... yes
checking for sqlite3_initialize()... yes
checking for sqlite3_backup_init()... yes
checking for sqlite3_column_database_name()... yes
checking for sqlite3_enable_load_extension()... yes
checking for sqlite3_load_extension()... yes
checking for sqlite3_open_v2()... yes
checking for sqlite3_prepare_v2()... yes
checking for sqlite3_int64 in sqlite3.h... yes
checking for sqlite3_uint64 in sqlite3.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling sqlite3.c
compiling exception.c
compiling backup.c
compiling database.c
compiling statement.c
statement.c: In function 'bind_param':
statement.c:261:7: warning: implicit declaration of function 'RBIGNUM' [-Wimplicit-function-declaration]
       if (RBIGNUM_LEN(value) * SIZEOF_BDIGITS <= 8) {
       ^
In file included from statement.c:1:0:
./sqlite3_ruby.h:16:34: error: invalid type argument of '->' (have 'int')
 #define RBIGNUM_LEN(x) RBIGNUM(x)->len
                                  ^
statement.c:261:11: note: in expansion of macro 'RBIGNUM_LEN'
       if (RBIGNUM_LEN(value) * SIZEOF_BDIGITS <= 8) {
           ^
statement.c:261:32: error: 'SIZEOF_BDIGITS' undeclared (first use in this function)
       if (RBIGNUM_LEN(value) * SIZEOF_BDIGITS <= 8) {
                                ^
statement.c:261:32: note: each undeclared identifier is reported only once for each function it appears in
statement.c: In function 'reset_bang':
statement.c:293:7: warning: variable 'status' set but not used [-Wunused-but-set-variable]
   int status;
       ^
statement.c: In function 'clear_bindings':
statement.c:313:7: warning: variable 'status' set but not used [-Wunused-but-set-variable]
   int status;
       ^
make: *** [statement.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.8 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.2.2/extensions/x86_64-linux/2.2.0/sqlite3-1.3.8/gem_make.out
An error occurred while installing sqlite3 (1.3.8), and Bundler cannot continue.
Make sure that `gem install sqlite3 -v '1.3.8'` succeeds before bundling.`

I updated the `sqlite3` version to `1.3.10` in `Gemfile.lock` and it compiled. Should I send a pull request?

Thanks in advance,
Max

**Comment by ne0h** [comment]
### Update:
I am trying to deploy promdash with Apache and mod_passenger. This is my config:

`<VirtualHost *:443>

        ServerName promdash.url
        DocumentRoot /srv/promdash/public

        SSLEngine on
        SSLProtocol all -SSLv2 -SSLv3
        SSLCipherSuite ALL:!ADH:!EXPORT:!SSLv2:RC4+RSA:+HIGH:+MEDIUM

        SSLCertificateFile file.crt
        SSLCertificateKeyFile file.key
        SSLCertificateChainFile file.pem

        RailsEnv production
        SetEnv GEM_HOME /usr/local/rvm/gems/ruby-2.2.2
        <Directory "/srv/promdash/public">
                Options FollowSymLinks
                Require all granted
        </Directory>
</VirtualHost>`

Stylesheets, javascript etc is missing when opening via safari (and firefox). I'm getting errors like this one:

`App 2073 stdout: I, [2015-08-13T15:05:12.812214 #2073]  INFO -- : Started GET "/" for 141.3.229.89 at 2015-08-13 15:05:12 +0200
App 2073 stdout: I, [2015-08-13T15:05:12.812800 #2073]  INFO -- : Processing by DirectoriesController#index as HTML
App 2073 stdout: I, [2015-08-13T15:05:12.814351 #2073]  INFO -- :   Rendered directories/index.html.erb within layouts/application (0.9ms)
App 2073 stdout: I, [2015-08-13T15:05:12.815087 #2073]  INFO -- :   Rendered layouts/_messages.html.erb (0.0ms)
App 2073 stdout: I, [2015-08-13T15:05:12.815232 #2073]  INFO -- : Completed 200 OK in 2ms (Views: 1.7ms | ActiveRecord: 0.2ms)
App 2073 stdout: I, [2015-08-13T15:05:12.887822 #2073]  INFO -- : Started GET "/stylesheets/application.css" for 141.3.229.89 at 2015-08-13 15:05:12 +0200
App 2073 stdout: F, [2015-08-13T15:05:12.888300 #2073] FATAL -- : 
App 2073 stdout: ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"):
App 2073 stdout:   actionpack (4.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
App 2073 stdout:   actionpack (4.1.7) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
App 2073 stdout:   railties (4.1.7) lib/rails/rack/logger.rb:38:in `call_app'
App 2073 stdout:   railties (4.1.7) lib/rails/rack/logger.rb:22:in `call'
App 2073 stdout:   actionpack (4.1.7) lib/action_dispatch/middleware/request_id.rb:21:in `call'
App 2073 stdout:   rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
App 2073 stdout:   rack (1.5.2) lib/rack/runtime.rb:17:in `call'
App 2073 stdout:   activesupport (4.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
App 2073 stdout:   actionpack (4.1.7) lib/action_dispatch/middleware/static.rb:84:in `call'
App 2073 stdout:   rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
App 2073 stdout:   railties (4.1.7) lib/rails/engine.rb:514:in `call'
App 2073 stdout:   railties (4.1.7) lib/rails/application.rb:144:in `call'
App 2073 stdout:   /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:94:in `process_request'
App 2073 stdout:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
App 2073 stdout:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 2073 stdout:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
App 2073 stdout:   /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
App 2073 stdout: 
App 2073 stdout: 
App 2073 stdout: I, [2015-08-13T15:05:12.976076 #2073]  INFO -- : Started GET "/javascripts/base.js" for 141.3.229.89 at 2015-08-13 15:05:12 +0200
App 2073 stdout: F, [2015-08-13T15:05:12.976616 #2073] FATAL -- : 
App 2073 stdout: ActionController::RoutingError (No route matches [GET] "/javascripts/base.js"):
App 2073 stdout:   actionpack (4.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
App 2073 stdout:   actionpack (4.1.7) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
App 2073 stdout:   railties (4.1.7) lib/rails/rack/logger.rb:38:in `call_app'
App 2073 stdout:   railties (4.1.7) lib/rails/rack/logger.rb:22:in `call'
App 2073 stdout:   actionpack (4.1.7) lib/action_dispatch/middleware/request_id.rb:21:in `call'
App 2073 stdout:   rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
App 2073 stdout:   rack (1.5.2) lib/rack/runtime.rb:17:in `call'
App 2073 stdout:   activesupport (4.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
App 2073 stdout:   actionpack (4.1.7) lib/action_dispatch/middleware/static.rb:84:in `call'
App 2073 stdout:   rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
App 2073 stdout:   railties (4.1.7) lib/rails/engine.rb:514:in `call'
App 2073 stdout:   railties (4.1.7) lib/rails/application.rb:144:in `call'
App 2073 stdout:   /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:94:in `process_request'
App 2073 stdout:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
App 2073 stdout:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 2073 stdout:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
App 2073 stdout:   /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
App 2073 stdout: 
App 2073 stdout:`

**Comment by juliusv** [comment]
@ne0h Yep, if the sqlite3 update helps, PR welcome to update that :)

Not sure about the Apache / Rails interaction there, but seems unrelated to this issue? Does it run standalone like described in the README.md?

**Comment by ne0h** [comment]
I needed to add `gem sqlite` to `Gemfile`, because I use `sqlite3` as a productive database backend. Should I include this in the pull request?

**Comment by grobie** [comment]
It's already part of the gemfile? I don't have access to the right syntax
right now, but something like `bundle install --with sqlite3` should do the
trick.

**Comment by ne0h** [comment]
`make build` only returns successfully when `gem 'sqlite'` is included in `Gemfile`.

**Comment by Anyoks** [comment]
@ne0h    Thanks alot. Your suggestion to update the Gemfile.lock works.
