### ISSUE TITLE
Being able to move graph between dashboards

### ISSUE THREAD

**Issue by crazydan** [prometheus/promdash#443]
It would be nice to be able to move graph between dashboards. So far the only way to achieve that is to recreate it from scratch on the new dashboard.

e.g. I've set up a graph with like 10 datasources but realized I put it in the wrong dashboard or I want later on to move it to another dashboard.

**Comment by stuartnelson3** [comment]
there is a clone functionality that allows you to take the graph setup from one dashboard and place it on another.

![image](https://cloud.githubusercontent.com/assets/1398104/9302457/eed2c8dc-44d6-11e5-99e3-3d1007bf3d5a.png)

![image](https://cloud.githubusercontent.com/assets/1398104/9302464/01756c42-44d7-11e5-8fdb-659341ded914.png)

selecting "clone" will add that widget to the dashboard you are currently on. you must save your dashboard to persist the changes.
