### ISSUE TITLE
restrict access to prom with basic auth

### ISSUE THREAD

**Issue by larserikfagernaes** [prometheus/promdash#447]
I've read through the documentation but cant seem to find a way to protect 
access to my.ip.adress:port. So annybody getting the url can se the graphs on my server. How to protect my server?

**Comment by matthiasr** [comment]
We generally don't support authentication for the various web interfaces – there's just too many possible ways. This is better handled by a reverse proxy (e.g. nginx) in front.

**Comment by larserikfagernaes** [comment]
Thanks!
