### ISSUE TITLE
Link to graph broken when using path in server URL

### ISSUE THREAD

**Issue by jonnenauha** [prometheus/promdash#450]
Noticed the `Datasources > Link to Graph in Prometheus` button link is broken if you use a path in the server url.

My server URL is `http://dash.example.com/prom/`
The link that button opens in a new tab is `http://dash.mapgets.com/promgraph#<fragment>`

It seems to strip the last fwd slash from the path + "graph". I dunno why without path it would work if it strips the first slash, that would become `http://dash.mapgets.comgraph#<fragment>` so there must be some special check for it.

**Comment by stuartnelson3** [comment]
:+1:
