### ISSUE TITLE
Graphs not rendering expressions

### ISSUE THREAD

**Issue by MrMMorris** [prometheus/promdash#452]
I ran into an issue similar to this before, but now I don't have a fix for it.

I hadn't taken a look at Promdash for a while and when I took a look today, none of the graphs had any metrics. This made sense to me because a lot of exporter ports had changed so I tried updating one of the graphs with the new ports. Still nothing. Tried cloning the Dashboard. Still nothing. Tried creating a new dashboard with the same expressions. Still nothing.

I know the expressions are right because they work in the server graph creator and the exporters are all healthy, so it must be something with Promdash.

I took a look at the JSON of my dashboard and the only thing that seems like it would matter is the `serverID`, but I don't know what this corresponds to or if I can change it.

Any ideas?

**Comment by matthiasr** [comment]
The ServerID corresponds to the list in the "Servers" tab – check that that list is correct? There have also been issues with trailing slashes in the past. What version are you using?

Also, try the breakout link next to the expression (not the widget permalink), it should take you to your Prometheus and this might give a hint as to what is wrong.

**Comment by stuartnelson3** [comment]
Checking for errors in the dev console is also helpful for diagnosing.

**Comment by juliusv** [comment]
Building PromDash from the latest Docker image, it does manage to query, but the expression dialog looks screwed up (scrollbar and broken autocomplete HTML element):

![promdash_glitch](https://cloud.githubusercontent.com/assets/538008/9960075/ba380668-5e18-11e5-8033-fe1dab91a728.png)

@stuartnelson3 do you have any context on these? Probably part of the bootstrap 3.3.5 update?

**Comment by juliusv** [comment]
(I opened a new issue for that: https://github.com/prometheus/promdash/issues/453)

**Comment by MrMMorris** [comment]
Thanks for the quick responses! This is why I love Prometheus :)

I don't know what version I'm using. Whatever was the `latest` docker tag 8 weeks ago.

@matthiasr it looks like on the Servers tab the only server there has a Name of "1". Where would `serverID` be getting '13' from?

The breakout link works and shows the graph I want.

Expression json:
```json
{
            "id": 0,
            "serverID": 13,
            "axisID": 1,
            "expression": "sum(rate(node_cpu{job='node',instance='10.0.0.205:33141',mode='system'}[1m])) * 100 / count(count by (cpu)(node_cpu{job='node',instance='10.0.0.205:33141'}))"
          },
```

**Comment by juliusv** [comment]
Ok, if the breakout view shows the graph you want, then we know already it's no problem related to the server ID.

Any JavaScript errors visible in the browser's debug console?

**Comment by MrMMorris** [comment]
@juliusv a whole bunch of these errors:
```
Mixed Content: The page at 'https://monitoring.company.org/load-testing-clone' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://52.3.215.128:9090/api/query_range?end=0&expr=sum(rate(node_cpu%7Bjob…Bjob%3D%27node%27,instance%3D%2710.0.0.205:33141%27%7D))&range=1800&step=9'. This request has been blocked; the content must be served over HTTPS.
```

I have ssl being terminated at my ELB.

**Comment by juliusv** [comment]
Ah, damn. So you need to either terminate both PromDash and Prometheus servers with HTTPS or both HTTP. See also: https://developer.mozilla.org/en-US/docs/Security/MixedContent/How_to_fix_website_with_mixed_content

There's nothing really that PromDash can do otherwise, as it's a browser-enforced security mechanism.

**Comment by juliusv** [comment]
You could also give this a try: http://wiki.sln.suny.edu/display/SLNKB/Enabling+mixed+content+in+Mozilla+Firefox

**Comment by MrMMorris** [comment]
@juliusv alright, so does that mean specifying my SSL certs in my nginx backend as well as the ELB?

**Comment by matthiasr** [comment]
You need to make your Prometheus reachable over SSL. I take it your setup is

Internet -> ELB (SSL termination) -> nginx (vhost routing)?

I think you don't need SSL in nginx. Just add a location or vhost in nginx
to proxy to <Prometheus IP>:9090. In other words, make Prometheus available
at https://monitoring-pronetheus.company.org/ or
https://monitoring.company.org/-/prometheus/ and change the PromDash server
URL to point at that.

I'm not sure what the auth situation is in this case.

**Comment by MrMMorris** [comment]
@matthiasr that worked! I had the server name as the public IP before. Changed it to https://monitoring-prometheus.company.org/ and updated the expressions to use the new server.

Thanks!
