### ISSUE TITLE
clicking on "Add Graph" does nothing. 

### ISSUE THREAD

**Issue by medyagh** [prometheus/promdash#487]
I am following the getting started doc, on Mac, I am using prometheus-1.5.0.darwin-amd64 
when I click "Add Graph" nothing happens.

in chrome's inspect I see
```
Uncaught ReferenceError: Handlebars is not defined
    at graph.js:6
```

that line is 
`Handlebars.registerHelper('pathPrefix', function() { return PATH_PREFIX; });`

**Comment by stuartnelson3** [comment]
Hm, this project doesn't use Handlebars, so I'm not sure what you're looking at. The file you reference (`graph.js`) doesn't have that code, either.

**Comment by medyagh** [comment]
I just re-did everything and here I screenshot for you 
<img width="974" alt="screen shot 2017-02-06 at 10 14 39 am" src="https://cloud.githubusercontent.com/assets/4564227/22655346/82009d6a-ec55-11e6-8772-14640d351f97.png">

**Comment by medyagh** [comment]
here is the location of the file if it helps debugging.
<img width="296" alt="screen shot 2017-02-06 at 10 21 17 am" src="https://cloud.githubusercontent.com/assets/4564227/22655562/279af144-ec56-11e6-9268-6726922231d3.png">

**Comment by stuartnelson3** [comment]
That's prometheus, not promdash. You should open this issue over there.
