### ISSUE TITLE
X-axis labels should make sense for the selected range

### ISSUE THREAD

**Issue by xla** [prometheus/promdash#5]
Currently the labels only should hours, even so a range greater than 24 hours is picked. The labels should be sensitive to the range. 

![screen shot 2013-11-01 at 3 01 32 pm](https://f.cloud.github.com/assets/1585/1453871/4c3bbe0c-42fe-11e3-99b2-04e643c27b1b.png)

**Comment by grobie** [comment]
Solved in the meantime.
