### ISSUE TITLE
Graph X-Axis range should be fixed to configured graph range

### ISSUE THREAD

**Issue by juliusv** [prometheus/promdash#58]
Currently, if we have e.g. only 1h worth of data, but the user configures a 2h graph range, the graph X-axis will scale to show only the 1h which we have data for. This is because the configured graph range is only used by the query to the Prometheus server, but Rickshaw only gets whatever data we got back from the server, without any knowledge of the intended graph range. This is confusing to users and should be fixed.

**Comment by grobie** [comment]
Solved in the meantime.
