### ISSUE TITLE
First graph is higher in fullscreen view

### ISSUE THREAD

**Issue by juliusv** [prometheus/promdash#71]
Steps to reproduce:

1. Create dashboard with at least two graphs
2. Enable fullscreen mode
3. The first graph is multiple pixels taller than the others and the layout of the other graphs around it is changed as a result:

![higher_first_graph](https://f.cloud.github.com/assets/538008/2309150/3e0687bc-a2cc-11e3-8b78-592d234fbccc.png)

**Comment by grobie** [comment]
Can't reproduce. Can this and #178 be close? @juliusv @stuartnelson3

**Comment by stuartnelson3** [comment]
:+1:

**Comment by juliusv** [comment]
Indeed, haven't seen this problem in a year or so. Closing.
