### ISSUE TITLE
 Show gaps in graph when data has long gaps

### ISSUE THREAD

**Issue by juliusv** [prometheus/promdash#82]
Same as this issue in Prometheus: https://github.com/prometheus/prometheus/issues/345

When there are missing samples in a timeseries where other timeseries do have samples, Rickshaw currently fills the missing samples with `0` values. The result is that a timeseries dropping to `0` is visually indistinguishable from a timeseries that is missing values. Missing values should be displayed as gaps instead.

**Comment by grobie** [comment]
Solved in the meantime.
